name: Update MLX Dataset

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_dataset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub transformers datasets
    - name: Run update script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python update_mlx_dataset.py
